### ISSUE TITLE
[Feature] Improve Product Search UX/UI

### ISSUE THREAD

**Issue by lesther-santana** [lesther-santana/carobarato-app#5]
### Context

Right now, it could be more intuitive for the user to enable the sidebar to create a comparison. For instance, if the sidebar closes, there are no explicit instructions or indications for reopening it. Moreover, the search bar near the products might be redundant when compared.

### Request

Could you improve the user experience with the comparisons and the search bars?

**Comment by Christonit** [comment]
Deployed
